importFiles:
    roles: {  }
    groups: {  }
    settings: {  }
    nodetypes:
        - src/Resources/node-types/Article.json
        - src/Resources/node-types/BasicBlock.json
        - src/Resources/node-types/GroupBlock.json
        - src/Resources/node-types/Neutral.json
        - src/Resources/node-types/Offer.json
        - src/Resources/node-types/Page.json
