color: '#db2525'
name: ArticleContainer
displayName: 'Article container'
visible: true
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: true
hidingNodes: true
hidingNonReachableNodes: false
fields: {  }
defaultTtl: 0
searchable: true
