color: '#00308a'
name: Article
displayName: Article
description: Article
visible: true
publishable: true
attributable: true
sortingAttributesByWeight: false
reachable: true
hidingNodes: false
hidingNonReachableNodes: true
fields:
    -
        name: content
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Your content'
        expanded: false
        position: 2.0
        nodeTypeName: Article
        type: markdown
    -
        name: realm_b_secret
        universal: false
        excludeFromSearch: false
        serializationGroups:
            - realm_b
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Secret realm_b'
        expanded: false
        position: 3.0
        nodeTypeName: Article
        type: string
    -
        name: realm_a_secret
        universal: false
        excludeFromSearch: false
        serializationGroups:
            - realm_a
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Secret realm_a'
        expanded: false
        position: 4.0
        nodeTypeName: Article
        type: string
    -
        name: blocks
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Blocks
        expanded: false
        position: 5.0
        nodeTypeName: Article
        defaultValues:
            - BasicBlock
            - GroupBlock
        type: children-nodes
    -
        name: unpublished_at
        universal: true
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: true
        visible: true
        label: 'Date de dépublication'
        expanded: false
        position: 6.0
        nodeTypeName: Article
        type: date-time
    -
        name: only_on_webresponse
        universal: false
        excludeFromSearch: false
        serializationGroups:
            - article_get_by_path
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Only on web response'
        expanded: false
        position: 7.0
        nodeTypeName: Article
        type: string
    -
        name: related_article
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        normalizationContext:
            groups:
                - related_articles
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Related article'
        expanded: false
        position: 8.0
        nodeTypeName: Article
        defaultValues:
            - Article
        type: nodes
defaultTtl: 15
searchable: true
