color: '#00308a'
name: Article
displayName: Article
description: Article
visible: true
publishable: true
attributable: true
sortingAttributesByWeight: false
reachable: true
fields:
    -
        name: content
        description: 'Your content'
        label: 'Your content'
        type: markdown
    -
        name: realm_b_secret
        serializationGroups:
            - realm_b
        label: 'Secret realm_b'
        type: string
    -
        name: realm_a_secret
        serializationGroups:
            - realm_a
        label: 'Secret realm_a'
        type: string
    -
        name: blocks
        label: Blocks
        defaultValues:
            - BasicBlock
            - GroupBlock
            - AliasBlock
        type: children-nodes
    -
        name: unpublished_at
        universal: true
        indexed: true
        label: 'Date de dépublication'
        type: date-time
    -
        name: only_on_webresponse
        serializationGroups:
            - article_get_by_path
        label: 'Only on web response'
        type: string
    -
        name: related_article
        serializationMaxDepth: 1
        serializationGroups:
            - related_articles
            - nodes_sources_base
        normalizationContext:
            groups:
                - related_articles
                - nodes_sources_base
        label: 'Related article'
        defaultValues:
            - Article
        type: nodes

