color: '#6369c2'
name: MenuLink
displayName: 'Lien du menu'
visible: false
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: link_external_url
        excludeFromSearch: true
        label: 'URL externe'
        type: string
    -
        name: link_internal_reference
        universal: true
        serializationGroups:
            - urls
        normalizationContext:
            groups:
                - urls
                - nodes_sources_base
        serializationMaxDepth: 1
        label: 'Référence au nœud (Page ou Bloc de page)'
        defaultValues:
            - Page
            - Article
        type: nodes
    -
        name: image
        label: Image
        type: documents
defaultTtl: 0
searchable: true
