color: '#947ccf'
name: Menu
displayName: Menu
description: null
visible: true
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: menu_items
        universal: false
        excludeFromSearch: false
        serializationExclusionExpression: null
        serializationGroups: {  }
        normalizationContext: null
        serializationMaxDepth: null
        excludedFromSerialization: false
        minLength: null
        maxLength: null
        indexed: false
        visible: true
        groupName: null
        label: 'Éléments du menu'
        placeholder: null
        description: null
        expanded: false
        position: 1.0
        nodeTypeName: Menu
        defaultValues:
            - Menu
            - MenuLink
            - Page
            - ArticleContainer
        type: children-nodes
defaultTtl: 0
searchable: true
