color: '#6369c2'
name: MenuLink
displayName: 'Lien du menu'
visible: false
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: link_external_url
        universal: false
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'URL externe'
        expanded: false
        position: 1.0
        nodeTypeName: MenuLink
        type: string
    -
        name: link_internal_reference
        universal: true
        excludeFromSearch: false
        serializationGroups:
            - urls
        normalizationContext:
            groups:
                - urls
                - nodes_sources_base
        serializationMaxDepth: 1
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Référence au nœud (Page ou Bloc de page)'
        expanded: false
        position: 2.0
        nodeTypeName: MenuLink
        defaultValues:
            - Page
            - Article
        type: nodes
    -
        name: image
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Image
        expanded: false
        position: 3.0
        nodeTypeName: MenuLink
        type: documents
defaultTtl: 0
searchable: true
