color: '#947ccf'
name: Menu
displayName: Menu
visible: true
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: menu_items
        label: 'Éléments du menu'
        defaultValues:
            - Menu
            - MenuLink
            - Page
            - ArticleContainer
        type: children-nodes
defaultTtl: 0
searchable: true
