color: '#a8a8a8'
name: Neutral
displayName: Neutral
description: Neutral
visible: true
publishable: false
attributable: false
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: number
        indexed: true
        label: Number
        type: integer
defaultTtl: 0
searchable: true
