color: '#a8a8a8'
name: Neutral
displayName: Neutral
description: Neutral
visible: true
publishable: false
attributable: false
sortingAttributesByWeight: false
reachable: false
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: number
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: true
        visible: true
        label: Number
        expanded: false
        position: 1.0
        nodeTypeName: Neutral
        type: integer
defaultTtl: 0
searchable: true
