color: '#ff0000'
name: Offer
displayName: Offer
description: Offer
visible: true
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: true
hidingNodes: false
hidingNonReachableNodes: false
fields:
    -
        name: vat
        label: VAT
        type: decimal
    -
        name: price
        indexed: true
        label: Price
        type: integer
    -
        name: geolocation
        universal: true
        label: Geolocation
        type: geographic.coordinates
    -
        name: multi_geolocation
        universal: true
        label: 'Multi geolocations'
        type: multiple.geographic.coordinates
    -
        name: layout
        universal: true
        excludeFromSearch: true
        indexed: true
        label: Layout
        placeholder: light
        defaultValues:
            - dark
        type: single-choice
defaultTtl: 0
searchable: true
