color: '#000000'
name: Page
displayName: Page
description: Page
visible: true
publishable: true
attributable: true
sortingAttributesByWeight: false
reachable: true
hidingNodes: false
hidingNonReachableNodes: true
fields:
    -
        name: content
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Content
        description: Content
        expanded: false
        position: 1.0
        nodeTypeName: Page
        type: markdown
    -
        name: sub_title
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Sub-title
        expanded: false
        position: 2.0
        nodeTypeName: Page
        type: string
    -
        name: children
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Nœuds enfants'
        expanded: false
        position: 3.0
        nodeTypeName: Page
        defaultValues:
            - BasicBlock
            - GroupBlock
            - ArticleFeedBlock
        type: children-nodes
    -
        name: color
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Page color'
        expanded: false
        position: 4.0
        nodeTypeName: Page
        type: colour
    -
        name: images
        universal: true
        excludeFromSearch: false
        serializationGroups:
            - realm_a
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Images
        expanded: false
        position: 5.0
        nodeTypeName: Page
        type: documents
    -
        name: header_image
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        groupName: Images
        label: 'Header image'
        expanded: false
        position: 6.0
        nodeTypeName: Page
        type: documents
    -
        name: over_title
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Overtitle
        expanded: false
        position: 7.0
        nodeTypeName: Page
        type: string
    -
        name: pictures
        universal: true
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        groupName: Images
        label: Pictures
        description: 'Picture for website'
        expanded: false
        position: 8.0
        nodeTypeName: Page
        type: documents
    -
        name: node_references
        universal: false
        excludeFromSearch: false
        serializationGroups:
            - page_get_by_path
        normalizationContext:
            groups:
                - page_get_by_path
                - urls
                - nodes_sources_base
        serializationMaxDepth: 1
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: References
        expanded: false
        position: 9.0
        nodeTypeName: Page
        type: nodes
    -
        name: sticky
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: true
        visible: true
        groupName: Boolean
        label: Sticky
        expanded: false
        position: 10.0
        nodeTypeName: Page
        type: boolean
    -
        name: stickytest
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: true
        visible: true
        groupName: Boolean
        label: 'Sticky test'
        expanded: false
        position: 11.0
        nodeTypeName: Page
        type: boolean
    -
        name: custom_form
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        maxLength: 1
        indexed: false
        visible: true
        label: 'Custom form'
        expanded: false
        position: 12.0
        nodeTypeName: Page
        type: custom-forms
    -
        name: users
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Reference to users'
        expanded: false
        position: 13.0
        nodeTypeName: Page
        defaultValues:
            classname: \RZ\Roadiz\CoreBundle\Entity\User
            displayable: getUsername
            alt_displayable: getEmail
            thumbnail: null
            searchable:
                - username
                - email
            orderBy:
                -
                    field: email
                    direction: ASC
            proxy:
                classname: App\Entity\PositionedPageUser
                self: nodeSource
                relation: user
                orderBy:
                    -
                        field: position
                        direction: ASC
        type: many-to-many
    -
        name: folder_references
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Reference to folders'
        expanded: false
        position: 14.0
        nodeTypeName: Page
        defaultValues:
            classname: RZ\Roadiz\CoreBundle\Entity\Folder
            displayable: getName
            alt_displayable: getFullPath
            searchable:
                - folderName
            orderBy:
                -
                    field: position
                    direction: ASC
        type: many-to-many
    -
        name: amount
        universal: true
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Amount
        expanded: false
        position: 15.0
        nodeTypeName: Page
        type: decimal
    -
        name: email_test
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Test email'
        expanded: false
        position: 16.0
        nodeTypeName: Page
        type: email
    -
        name: settings
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Settings
        expanded: false
        position: 17.0
        nodeTypeName: Page
        defaultValues:
            classname: Themes\Rozier\Explorer\SettingsProvider
        type: multiple-provider
    -
        name: folder
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Folder simple'
        expanded: false
        position: 18.0
        nodeTypeName: Page
        defaultValues:
            classname: Themes\Rozier\Explorer\FoldersProvider
        type: single-provider
    -
        name: country
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Country
        expanded: false
        position: 19.0
        nodeTypeName: Page
        type: country
    -
        name: geolocation
        universal: true
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: Geolocation
        expanded: false
        position: 20.0
        nodeTypeName: Page
        type: geographic.coordinates
    -
        name: multi_geolocation
        universal: true
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        groupName: Geo
        label: 'Multi geolocations'
        expanded: false
        position: 21.0
        nodeTypeName: Page
        type: multiple.geographic.coordinates
    -
        name: layout
        universal: true
        excludeFromSearch: true
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: true
        visible: true
        label: Layout
        placeholder: light
        expanded: false
        position: 22.0
        nodeTypeName: Page
        defaultValues:
            - dark
            - transparent
        type: single-choice
    -
        name: main_user
        universal: false
        excludeFromSearch: false
        serializationGroups: {  }
        excludedFromSerialization: false
        indexed: false
        visible: true
        label: 'Main user'
        expanded: false
        position: 23.0
        nodeTypeName: Page
        defaultValues:
            classname: \RZ\Roadiz\CoreBundle\Entity\User
            displayable: getUsername
            alt_displayable: getEmail
            thumbnail: null
            searchable:
                - username
                - email
            orderBy:
                -
                    field: email
                    direction: ASC
        type: many-to-one
defaultTtl: 15
searchable: true
