color: '#000000'
name: Page
displayName: Page
description: Page
visible: true
publishable: false
attributable: true
sortingAttributesByWeight: false
reachable: true
hidingNodes: false
hidingNonReachableNodes: true
highlighted: true
fields:
    -
        name: sub_title
        description: Sub-title description
        label: Sub-title
        type: string
        required: true
    -
        name: content
        label: Content
        description: Content
        defaultValues:
            allow_h1: false
            allow_h2: false
            allow_h3: false
            allow_h4: false
            allow_h5: false
            allow_h6: false
            allow_list: false
            allow_blockquote: false
        type: markdown
    -
        name: color
        universal: true
        excludeFromSearch: true
        label: 'Page color'
        type: colour
    -
        name: children
        label: 'Nœuds enfants'
        defaultValues:
            - BasicBlock
            - GroupBlock
            - ArticleFeedBlock
            - AliasBlock
        required: true
        type: children-nodes
    -
        name: images
        universal: true
        serializationGroups:
            - realm_a
        label: Images
        required: true
        type: documents
    -
        name: header_image
        groupName: Images
        label: 'Header image'
        type: documents
    -
        name: over_title
        label: Overtitle
        type: string
    -
        name: pictures
        universal: true
        groupName: Images
        label: Pictures
        description: 'Picture for website'
        type: documents
    -
        name: node_references
        serializationGroups:
            - page_get_by_path
        normalizationContext:
            groups:
                - page_get_by_path
                - urls
                - nodes_sources_base
        serializationMaxDepth: 1
        label: References
        required: true
        type: nodes
    -
        name: sticky
        universal: true
        excludeFromSearch: true
        indexed: true
        groupName: Boolean
        label: Sticky
        type: boolean
    -
        name: stickytest
        universal: true
        excludeFromSearch: true
        indexed: true
        groupName: Boolean
        label: 'Sticky test'
        type: boolean
    -
        name: custom_form
        maxLength: 1
        label: 'Custom form'
        type: custom-forms
    -
        name: users
        universal: true
        excludeFromSearch: true
        label: 'Reference to users'
        defaultValues:
            classname: \RZ\Roadiz\CoreBundle\Entity\User
            displayable: getUsername
            alt_displayable: getEmail
            thumbnail: null
            searchable:
                - username
                - email
            orderBy:
                -
                    field: email
                    direction: asc
            proxy:
                classname: App\Entity\PositionedPageUser
                self: nodeSource
                relation: user
                orderBy:
                    -
                        field: position
                        direction: ASC
        required: true
        type: many-to-many
    -
        name: folder_references
        label: 'Reference to folders'
        required: true
        defaultValues:
            classname: RZ\Roadiz\CoreBundle\Entity\Folder
            displayable: getName
            alt_displayable: getFullPath
            searchable:
                - folderName
            orderBy:
                -
                    field: position
                    direction: ASC
        type: many-to-many
    -
        name: amount
        universal: true
        label: Amount
        type: decimal
    -
        name: email_test
        label: 'Test email'
        type: email
    -
        name: settings
        label: Settings
        defaultValues:
            classname: RZ\Roadiz\RozierBundle\Explorer\Provider\SettingsProvider
        type: multiple-provider
    -
        name: contacts
        label: Contacts
        defaultValues:
            entry_type: App\Form\ContactFormType
        type: collection
    -
        name: folder
        label: 'Folder simple'
        defaultValues:
            classname: RZ\Roadiz\RozierBundle\Explorer\Provider\FoldersProvider
        type: single-provider
    -
        name: country
        universal: true
        excludeFromSearch: true
        label: Country
        type: country
    -
        name: geolocation
        universal: true
        label: Geolocation
        type: geographic.coordinates
    -
        name: multi_geolocation
        universal: true
        groupName: Geo
        label: 'Multi geolocations'
        type: multiple.geographic.coordinates
    -
        name: layout
        universal: true
        excludeFromSearch: true
        indexed: true
        label: Layout
        placeholder: light
        defaultValues:
            - dark
            - transparent
        type: single-choice
    -
        name: main_user
        label: 'Main user'
        required: true
        defaultValues:
            classname: \RZ\Roadiz\CoreBundle\Entity\User
            displayable: getUsername
            alt_displayable: getEmail
            thumbnail: null
            searchable:
                - username
                - email
            orderBy:
                -
                    field: email
                    direction: ASC
        type: many-to-one
defaultTtl: 15
searchable: true
