api_platform:
    title:       "%env(string:APP_TITLE)%"
    description: "%env(string:APP_DESCRIPTION)%"
    version:     '%env(string:APP_VERSION)%'
    enable_swagger_ui: true
    enable_re_doc: true
    graphql:
        introspection: '%kernel.debug%'
        graphiql:
            enabled: false
        graphql_playground:
            enabled: true
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/GeneratedEntity'
            - '%kernel.project_dir%/lib/RoadizCoreBundle/src/Entity'
            - '%kernel.project_dir%/lib/RoadizUserBundle/src/Api/Dto'
            - '%kernel.project_dir%/vendor/rezozero/tree-walker/src'
            - '%kernel.project_dir%/config/api_resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: itemsPerPage

    defaults:
        stateless: true
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: false
        enable_max_depth: true
        normalization_context:
            skip_null_values: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 15
        pagination_maximum_items_per_page: 50
        cache_headers:
            etag: true
            public: true
            max_age: '%env(int:HTTP_CACHE_MAX_AGE)%'
            shared_max_age: '%env(int:HTTP_CACHE_SHARED_MAX_AGE)%'
            vary: [ 'Accept', 'Authorization', 'Origin', 'Accept-Encoding', 'Content-Type' ]

when@prod:
    api_platform:
        graphql:
            introspection: false
            graphiql:
                enabled: false
            graphql_playground:
                enabled: false
        http_cache:
            invalidation:
                enabled: true
                varnish_urls: [ '%env(VARNISH_URL)%' ]
