api_platform:
    title:       "Roadiz development app"
    description: "Roadiz development app"
    version:     '%env(string:APP_VERSION)%'
    enable_swagger_ui: false
    enable_re_doc: true
    graphql:
        graphiql:
            enabled: false
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/GeneratedEntity'
            - '%kernel.project_dir%/lib/RoadizCoreBundle/src/Entity'
            - '%kernel.project_dir%/vendor/rezozero/tree-walker/src'
            - '%kernel.project_dir%/config/api_resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 15 # Default value
            maximum_items_per_page: 50
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage

    http_cache:
        # Automatically generate etags for API responses.
        etag: true
        public: true
        # Default value for the response max age.
        max_age: '%env(int:HTTP_CACHE_MAX_AGE)%'
        # Default value for the response shared (proxy) max age.
        shared_max_age: '%env(int:HTTP_CACHE_SHARED_MAX_AGE)%'
        # Default values of the "Vary" HTTP header.
        vary: [ 'Accept', 'Authorization', 'Origin', 'Accept-Encoding', 'Content-Type' ]
#        invalidation:
#            enabled: false
#            varnish_urls: [ '%env(VARNISH_URL)%' ]
    defaults:
        cache_headers:
            public: true
            max_age: '%env(int:HTTP_CACHE_MAX_AGE)%'
            shared_max_age: '%env(int:HTTP_CACHE_SHARED_MAX_AGE)%'
            vary: [ 'Accept', 'Authorization', 'Origin', 'Accept-Encoding', 'Content-Type' ]
