framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - '%kernel.project_dir%/lib/RoadizRozierBundle/public'
        missing_import_mode: strict
        public_prefix: '/static/'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
