framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            'lib/RoadizRozierBundle/static/': 'bundles/roadizrozier'
        missing_import_mode: strict
        public_prefix: '/static/'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
