# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    trusted_proxies: '%env(string:TRUSTED_PROXIES)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        name: roadiz_core_app
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    serializer:
        circular_reference_handler: 'RZ\Roadiz\CoreBundle\Serializer\CircularReferenceHandler'
        max_depth_handler: 'RZ\Roadiz\CoreBundle\Serializer\CircularReferenceHandler'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    rate_limiter:
        contact_form:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minutes', amount: 5 }
            cache_pool: 'cache.contact_form_limiter'
        custom_form:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minutes', amount: 5 }
            cache_pool: 'cache.custom_form_limiter'
        user_signup:
            policy: 'token_bucket'
            limit: 5
            rate: { interval: '1 minutes', amount: 3 }
            cache_pool: 'cache.user_signup_limiter'
        password_request:
            policy: 'token_bucket'
            limit: 3
            rate: { interval: '1 minutes', amount: 3 }
            cache_pool: 'cache.password_request_limiter'
        password_reset:
            policy: 'token_bucket'
            limit: 3
            rate: { interval: '1 minutes', amount: 3 }
            cache_pool: 'cache.password_reset_limiter'

    csrf_protection:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        php_errors:
            # E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
            log: 22519
