monolog:
    channels:
        - searchEngine
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            solr:
                type: stream
                path: "%kernel.logs_dir%/solr.%kernel.environment%.log"
                level: debug
                channels: [ "searchEngine" ]
            messenger:
                type: stream
                path: "%kernel.logs_dir%/messenger.%kernel.environment%.log"
                level: debug
                channels: ["messenger"]
            security:
                type: stream
                path: "%kernel.logs_dir%/security.%kernel.environment%.log"
                level: debug
                channels: ["security"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!deprecation"]
            custom:
                type: service
                id: RZ\Roadiz\CoreBundle\Logger\DoctrineHandler
                level: info
                channels: [ "app" ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!event", "!doctrine", "!deprecation"]
            nested:
                type: stream
                path: php://stderr
                level: info
                formatter: monolog.formatter.json
                channels: ["!event", "!doctrine", "!deprecation"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
