roadiz_core:
    appNamespace: '%env(string:APP_NAMESPACE)%'
    appVersion: '%env(string:APP_VERSION)%'
    healthCheckToken: '%env(string:APP_HEALTH_CHECK_TOKEN)%'
    staticDomainName: ~
    documentsLibDir: 'lib/Documents/src'
    useNativeJsonColumnType: true
    useGravatar: false
    useEmailReplyTo: true
    useDocumentDto: true
    helpExternalUrl: 'https://docs.roadiz.io'
    customPublicScheme: '%env(string:APP_CUSTOM_PUBLIC_SCHEME)%'
    customPreviewScheme: '%env(string:APP_CUSTOM_PREVIEW_SCHEME)%'
    useConstraintViolationList: true
    customFormPostOperationName: 'api_custom_forms_item_post'
    medias:
        unsplash_client_id: '%env(string:APP_UNSPLASH_CLIENT_ID)%'
        soundcloud_client_id: '%env(string:APP_SOUNDCLOUD_CLIENT_ID)%'
        google_server_id: '%env(string:APP_GOOGLE_SERVER_ID)%'
        ffmpeg_path: '%env(string:APP_FFMPEG_PATH)%'
    captcha:
        private_key: '%env(string:APP_CAPTCHA_PRIVATE_KEY)%'
        public_key: '%env(string:APP_CAPTCHA_PUBLIC_KEY)%'
        verify_url: '%env(string:APP_CAPTCHA_VERIFY_URL)%'
    inheritance:
        type: single_table
#    reverseProxyCache:
#        # Test Varnish invalidation on dev too
#        frontend:
#            default:
#                host: '%env(VARNISH_URL)%'
#                domainName: '%env(VARNISH_DOMAIN)%'
#        cloudflare:
#            zone: '%env(string:APP_CLOUDFLARE_ZONE)%'
#            bearer: '%env(string:APP_CLOUDFLARE_BEARER)%'
