roadiz_core:
    appNamespace: '%env(string:APP_NAMESPACE)%'
    staticDomainName: ~
    useNativeJsonColumnType: true
    security:
        private_key_name: default
    themes: []
    inheritance:
        type: single_table
    reverseProxyCache:
        frontend:
            default:
                host: '127.0.0.1:8081'
                domainName: roadiz-core-bundle.test
    solr:
        timeout: 3
        endpoints:
            docker:
                host: 127.0.0.1
                core: roadiz
                port: 8983
                path: /


