roadiz_core:
    appNamespace: '%env(string:APP_NAMESPACE)%'
    appVersion: '%env(string:APP_VERSION)%'
    healthCheckToken: '%env(string:APP_HEALTH_CHECK_TOKEN)%'
    staticDomainName: ~
    documentsLibDir: 'lib/Documents/src'
    useNativeJsonColumnType: true
    useGravatar: false
    medias:
        unsplash_client_id: '%env(string:APP_UNSPLASH_CLIENT_ID)%'
        soundcloud_client_id: '%env(string:APP_SOUNDCLOUD_CLIENT_ID)%'
        google_server_id: '%env(string:APP_GOOGLE_SERVER_ID)%'
        recaptcha_private_key: '%env(string:APP_RECAPTCHA_PRIVATE_KEY)%'
        recaptcha_public_key: '%env(string:APP_RECAPTCHA_PUBLIC_KEY)%'
        ffmpeg_path: '%env(string:APP_FFMPEG_PATH)%'
    inheritance:
        type: single_table

#    solr:
#        timeout: 3
#        endpoints:
#            docker:
#                host: '%env(string:SOLR_HOST)%'
#                core: '%env(string:SOLR_CORE_NAME)%'
#                port: '%env(string:SOLR_PORT)%'
#                path: /

    reverseProxyCache:
        # Test Varnish invalidation on dev too
        frontend:
            default:
                host: '%env(VARNISH_URL)%'
                domainName: '%env(VARNISH_DOMAIN)%'
#        cloudflare:
#            zone: '%env(string:APP_CLOUDFLARE_ZONE)%'
#            bearer: '%env(string:APP_CLOUDFLARE_BEARER)%'
