name: roadiz-dev
services:
    db:
        build:
            target: mysql
            args:
                UID: ${UID:-1000}
        networks:
            - default
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db_name}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}

    db-test:
        build:
            target: mysql
            args:
                UID: ${UID:-1000}
        networks:
            - default
        volumes:
            - "db-test:/var/lib/mysql"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_TEST_DATABASE:-db_name_test}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}

    mariadb-test:
        build:
            target: mariadb
            args:
                UID: ${UID:-1000}
        networks:
            - default
        volumes:
            - "mariadb-test:/var/lib/mysql"
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 1
            MARIADB_DATABASE: ${MARIADB_TEST_DATABASE:-db_name_test}
            MARIADB_USER: ${MARIADB_USER:-db_user}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-db_password}

#    pma:
#        image: phpmyadmin:5.2.1
#        environment:
#            PMA_HOST: db
#            UPLOAD_LIMIT: 64M
#            PMA_USER: ${MYSQL_USER:-db_user}
#            PMA_PASSWORD: ${MYSQL_PASSWORD:-db_password}
#        depends_on:
#            - db

    solr:
        image: solr:9-slim
#        volumes:
#            - "solr-standalone:/var/solr"
#        command:
#            - solr-precreate
#            - ${SOLR_CORE_NAME}
# --- Use SolrCloud mode if you want to use multiple Solr nodes
#        volumes:
#            - solr-cloud:/var/solr
#        environment:
#            ZK_HOST: "zoo:2181"
#        depends_on: [ zoo ]
#
#    zoo:
#        image: zookeeper:3.9
#        environment:
#            ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

    redis:
        image: redis:7-alpine
        volumes:
            - "redis:/data"
        networks:
            - default

    app: &app_template
        # Need to pass all vars to docker env for Crontab and supervisor scripts
        env_file: "./.env.local"
        build:
            target: php-dev
            args:
                UID: ${UID:-1000}
        depends_on:
            - db
            - solr
            - redis
        volumes:
            - ./:/app
        networks:
            - default
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_CS_FIXER_IGNORE_ENV: 1
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            UID: ${UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}

    worker:
        <<: *app_template
        build:
            target: php-dev
            args:
                UID: ${UID:-1000}
        mem_limit: 1g
        restart: unless-stopped
        entrypoint: ["php", "-d", "memory_limit=-1", "/app/bin/console", "messenger:consume", "async", "--time-limit=600", "--profile"]

    scheduler:
        <<: *app_template
        build:
            target: php-dev
            args:
                UID: ${UID:-1000}
        mem_limit: 1g
        restart: unless-stopped
        entrypoint: ["php", "-d", "memory_limit=-1", "/app/bin/console", "messenger:consume", "scheduler_default", "--time-limit=600", "--profile"]

    nginx:
        build:
            target: nginx-dev
            args:
                UID: ${UID:-1000}
        depends_on:
            - app
        links:
            - app:app
        volumes:
            # Need to share all app files for relative symlink to work in development
            - ./:/app

    varnish:
        build:
            target: varnish
        depends_on:
            - nginx

    mailer:
        hostname: mailer
        image: axllent/mailpit

networks:
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/24

volumes:
    db-test:
    mariadb-test:
    redis:
#    solr-standalone:
#    solr-cloud:
