name: roadiz-dev
services:
    db:
        build:
            target: mysql
            args:
                UID: ${UID:-1000}
        networks:
            - default
        volumes:
            - "./.data/db:/var/lib/mysql:delegated"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db_name}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}

    db-test:
        build:
            target: mysql
            args:
                UID: ${UID:-1000}
        networks:
            - default
        volumes:
            - "./.data/db_test:/var/lib/mysql:delegated"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_TEST_DATABASE:-db_name_test}
            MYSQL_USER: ${MYSQL_USER:-db_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}

    pma:
        image: phpmyadmin:5.2.1
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 64M
            PMA_USER: ${MYSQL_USER:-db_user}
            PMA_PASSWORD: ${MYSQL_PASSWORD:-db_password}
        depends_on:
            - db
        networks:
            - frontproxynet
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_pma.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.rule=Host(${HOSTNAME_PMA})"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.service=${APP_NAMESPACE}_pma"

    solr:
        hostname: solr
        build:
            # Custom image for file permissions
            target: solr
            args:
                UID: ${UID:-1000}
        volumes:
            - "solr_data:/var/solr:delegated"
        command:
            - solr-precreate
            - ${SOLR_CORE_NAME}
        networks:
            - frontproxynet
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.port=8983"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_solr.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.rule=Host(${HOSTNAME_SOLR})"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.service=${APP_NAMESPACE}_solr"

    redis:
        image: redis:7-alpine
        networks:
            - default

    app: &app_template
        hostname: app
        # Need to pass all vars to docker env for Crontab and supervisor scripts
        env_file: "./.env.local"
        build:
            target: php-dev
            args:
                UID: ${UID:-1000}
        depends_on:
            - db
            - solr
            - redis
        volumes:
            - ./:/app:cached
        networks:
            - default
        environment:
            APP_CACHE: ${APP_CACHE}
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            UID: ${UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}

    worker:
        <<: *app_template
        hostname: app-worker
        # Need to restart worker every 10 minutes
        restart: unless-stopped
        entrypoint: ["php", "/app/bin/console", "messenger:consume", "async", "--time-limit=600"]

    cron:
        <<: *app_template
        build:
            target: cron-dev
            args:
                UID: ${UID:-1000}
        hostname: app-cron
        restart: unless-stopped

    nginx:
        build:
            target: nginx-dev
            args:
                UID: ${UID:-1000}
        depends_on:
            - app
        volumes:
            # Need to share all app files for relative symlink to work in development
            - ./:/app:cached
        networks:
            - default
            - frontproxynet
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.passhostheader=true"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.path=/health-check"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.interval=10s"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.timeout=3s"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.headers.x-health-check=${APP_HEALTH_CHECK_TOKEN}"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}.rule=Host(${HOSTNAME})"
            - "traefik.http.routers.${APP_NAMESPACE}.service=${APP_NAMESPACE}"
            # Listen HTTPS
            - "traefik.http.routers.${APP_NAMESPACE}_secure.entrypoints=https"
            - "traefik.http.routers.${APP_NAMESPACE}_secure.rule=Host(${HOSTNAME})"
            - "traefik.http.routers.${APP_NAMESPACE}_secure.tls=true"
            - "traefik.http.routers.${APP_NAMESPACE}_secure.service=${APP_NAMESPACE}"

    varnish:
        build:
            target: varnish
        networks:
            - default
            - frontproxynet
        depends_on:
            - nginx
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.rule=Host(${HOSTNAME_VARNISH})"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.service=${APP_NAMESPACE}_varnish"
            # Listen HTTPS
            - "traefik.http.routers.${APP_NAMESPACE}_varnish_secure.entrypoints=https"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish_secure.rule=Host(${HOSTNAME_VARNISH})"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish_secure.tls=true"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish_secure.service=${APP_NAMESPACE}_varnish"

    mailer:
        hostname: mailer
        image: axllent/mailpit
        networks:
            - frontproxynet
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.port=8025"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.rule=Host(${HOSTNAME_MAILER})"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.service=${APP_NAMESPACE}_mailer"

networks:
    frontproxynet:
        external: true
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/24

volumes:
    solr_data:
