appArticlesListPage:
    path:     /list
    defaults:
        _controller: App\Controller\Admin\ArticleController::defaultAction

appArticlesAddPage:
    path:     /add
    defaults:
        _controller: App\Controller\Admin\ArticleController::addAction


appArticlesBulkDeletePage:
    methods: [GET, POST]
    path:     /bulk-delete
    defaults:
        _controller: App\Controller\Admin\ArticleController::bulkDeleteAction
appArticlesBulkPublishPage:
    methods: [GET, POST]
    path:     /bulk-publish
    defaults:
        _controller: App\Controller\Admin\ArticleController::bulkPublishAction
appArticlesBulkUnpublishPage:
    methods: [GET, POST]
    path:     /bulk-unpublish
    defaults:
        _controller: App\Controller\Admin\ArticleController::bulkUnpublishAction
