---
RZ\Roadiz\CoreBundle\Entity\Document:
    attributes:
        output: RZ\Roadiz\CoreBundle\Api\Dto\DocumentOutput
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ["urls", "document_display", "document_display_sources"]
                enable_max_depth: true
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["urls", "document", "document_display", "document_folders", "document_display_sources"]
                enable_max_depth: true

