---
RZ\Roadiz\CoreBundle\Entity\Node:
    shortName: Node
    attributes:
        output: RZ\Roadiz\CoreBundle\Api\Dto\NodeOutput
    collectionOperations: []
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["node", "document_display"]
                enable_max_depth: true
