---
RZ\Roadiz\CoreBundle\Entity\NodesSources:
    iri: NodesSources
    shortName: NodesSources
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ["nodes_sources_default", "urls", "tag_base", "translation_base", "document_display"]

    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["nodes_sources", "urls", "tag_base", "translation_base", "document_display"]
        getByPath:
            method: 'GET'
            path: '/web_response_by_path'
            read: false
            controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
            normalization_context:
                groups: [ "web_response", "nodes_sources", "urls", "tag_base", "translation_base", "document_display" ]
            openapi_context:
                summary: Get a NodesSources resource by its path wrapped in a WebResponse object
                description: |
                    Get a NodesSources resource by its path wrapped in a WebResponse
                parameters:
                    -   type: string
                        name: path
                        in: query
                        required: true
                        description: NodesSources path, or `/` for home page
                        schema:
                            type: string
