resources:
    RZ\Roadiz\CoreBundle\Entity\Node:
        # Needed when using GraphQL
        shortName: Node
        graphQlOperations:
            - class: ApiPlatform\Metadata\GraphQl\Query
            - class: ApiPlatform\Metadata\GraphQl\QueryCollection
        operations:
            ApiPlatform\Metadata\Get:
                method: 'GET'
                normalizationContext:
                    groups: ["node", "document_display"]
                    enable_max_depth: true
