---
RZ\Roadiz\CoreBundle\Entity\Node:
    shortName: Node
    collectionOperations: []
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["node", "document_display"]
                enable_max_depth: true
