App\GeneratedEntity\NSArticle:
    types:
        - Article
    operations:
        article_get_collection:
            method: GET
            class: ApiPlatform\Metadata\GetCollection
            shortName: Article
            normalizationContext:
                enable_max_depth: true
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
        article_archives_collection:
            method: GET
            class: ApiPlatform\Metadata\GetCollection
            shortName: Article
            uriTemplate: /articles/archives
            extraProperties:
                archive_enabled: true
            openapiContext:
                summary: 'Retrieve all Article ressources archives months and years'
        article_get:
            method: GET
            class: ApiPlatform\Metadata\Get
            shortName: Article
            normalizationContext:
                groups:
                    - nodes_sources
                    - node_listing
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
