App\GeneratedEntity\NSArticle:
    iri: Article
    shortName: Article
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display

        archives:
            method: 'GET'
            path: '/articles/archives'
            read: false
            controller: RZ\Roadiz\CoreBundle\Api\Controller\NodesSourcesArchivesController
            pagination_enabled: false
            defaults:
                resource_date_field: publishedAt
            normalization_context:
                pagination_enabled: false
                groups:
                    - get
                    - archives
            openapi_context:
                summary: Get available Article archives
                parameters: ~
                description: |
                    Get available Article archives

    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display

        getByPath:
            method: GET
            normalization_context:
                groups:
                    - web_response
                    - position
                    - walker
                    - walker_level
                    - walker_metadata
                    - meta
                    - children
                    - children_count
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
