App\GeneratedEntity\NSArticle:
    types:
        - Article
    operations:
        article_get_collection:
            method: GET
            class: ApiPlatform\Metadata\GetCollection
            shortName: Article
            normalizationContext:
                enable_max_depth: true
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
        article_archives_collection:
            method: GET
            class: ApiPlatform\Metadata\GetCollection
            shortName: Article
            uriTemplate: /articles/archives
            extraProperties:
                archive_enabled: true
            openapiContext:
                summary: 'Retrieve all Article ressources archives months and years'
        article_get:
            method: GET
            class: ApiPlatform\Metadata\Get
            shortName: Article
            normalizationContext:
                groups:
                    - nodes_sources
                    - node_listing
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
        article_get_by_path:
            method: GET
            class: ApiPlatform\Metadata\Get
            uriTemplate: /web_response_by_path
            read: false
            controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
            normalizationContext:
                pagination_enabled: false
                enable_max_depth: true
                groups:
                    - nodes_sources
                    - node_listing
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
                    - web_response
                    - walker
                    - walker_level
                    - walker_metadata
                    - meta
                    - children
            openapiContext:
                tags:
                    - WebResponse
                summary: 'Get a resource by its path wrapped in a WebResponse object'
                description: 'Get a resource by its path wrapped in a WebResponse'
                parameters:
                    - { type: string, name: path, in: query, required: true, description: 'Resource path, or `/` for home page', schema: { type: string } }
