App\GeneratedEntity\NSMenuLink:
    types:
        - MenuLink
    operations:
        ApiPlatform\Metadata\Get:
            method: GET
            shortName: MenuLink
            normalizationContext:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
