App\GeneratedEntity\NSMenu:
    types:
        - Menu
    operations:
        ApiPlatform\Metadata\Get:
            method: GET
            shortName: Menu
            normalizationContext:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
