App\GeneratedEntity\NSNeutral:
    types:
        - Neutral
    operations:
        neutral_get:
            method: GET
            class: ApiPlatform\Metadata\Get
            shortName: Neutral
            normalizationContext:
                groups:
                    - nodes_sources
                    - node_listing
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
