App\GeneratedEntity\NSNeutral:
    types:
        - Neutral
    operations:
        ApiPlatform\Metadata\Get:
            method: GET
            shortName: Neutral
            normalizationContext:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
