App\GeneratedEntity\NSOffer:
    iri: Offer
    shortName: Offer
    collectionOperations:
        get:
            method: GET
            normalization_context:
                enable_max_depth: true
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
        getByPath:
            method: 'GET'
            path: '/web_response_by_path'
            read: false
            controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
            pagination_enabled: false
            normalization_context:
                enable_max_depth: true
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
                    - web_response
                    - walker
                    - walker_level
                    - walker_metadata
                    - meta
                    - children
                    - children_count
