App\GeneratedEntity\NSPage:
    iri: Page
    shortName: Page
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display

        getByPath:
            normalization_context:
                groups:
                    - web_response
                    - position
                    - walker
                    - walker_level
                    - walker_metadata
                    - meta
                    - children
                    - children_count
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
