
App\GeneratedEntity\NSPage:
    iri: Page
    shortName: Page
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                jsonld_embed_context: false
                groups: ["nodes_sources_default", "urls", "tag_base", "translation_base", "document_display"]
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                jsonld_embed_context: false
                groups: ["nodes_sources", "urls", "tag_base", "translation_base", "document_display"]
