App\GeneratedEntity\NSPage:
    iri: Page
    shortName: Page
    collectionOperations:
        get:
            method: GET
            normalization_context:
                enable_max_depth: true
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
                    - nodes_sources_images
                    - nodes_sources_boolean
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
                    - nodes_sources_images
                    - nodes_sources_boolean
        getByPath:
            method: GET
            normalization_context:
                enable_max_depth: true
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - document_thumbnails
                    - document_display_sources
                    - nodes_sources_images
                    - nodes_sources_boolean
                    - web_response
                    - walker
                    - walker_level
                    - walker_metadata
                    - meta
                    - children
                    - children_count
