resources:
    RZ\Roadiz\CoreBundle\Entity\Tag:
        shortName: Tag
        types:
            - Tag
        operations:
            ApiPlatform\Metadata\GetCollection:
                method: "GET"
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - tag_base

