resources:
    RZ\Roadiz\CoreBundle\Entity\Tag:
        graphQlOperations:
            - class: ApiPlatform\Metadata\GraphQl\Query
            - class: ApiPlatform\Metadata\GraphQl\QueryCollection
        operations:
            ApiPlatform\Metadata\GetCollection:
                method: "GET"
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - tag_base

            ApiPlatform\Metadata\Get:
                method: 'GET'
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - tag
                        - tag_base
                        - tag_parent
