resources:
    RZ\Roadiz\CoreBundle\Entity\Translation:
        shortName: Translation
        types:
            - Translation
        operations:
            ApiPlatform\Metadata\GetCollection:
                method: "GET"
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - translation_base
