resources:
    RZ\Roadiz\CoreBundle\Entity\Translation:
        shortName: Translation
        types:
            - Translation
        operations:
            ApiPlatform\Metadata\GetCollection:
                method: "GET"
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - translation_base

            translate:
                class: ApiPlatform\Metadata\Post
                method: "POST"
                uriTemplate: '/translations/translate'
                input: RZ\Roadiz\RozierBundle\Translator\TranslatorDto
                output: RZ\Roadiz\RozierBundle\Translator\TranslatorOutput
                controller: RZ\Roadiz\RozierBundle\Translator\DeeplTranslatorController::translate
                openapiContext:
                    summary: Translate text using DeepL API

            rephrase:
                class: ApiPlatform\Metadata\Post
                method: "POST"
                uriTemplate: '/translations/rephrase'
                input: RZ\Roadiz\RozierBundle\Translator\TranslatorDto
                output: RZ\Roadiz\RozierBundle\Translator\TranslatorOutput
                controller: RZ\Roadiz\RozierBundle\Translator\DeeplTranslatorController::rephrase
                openapiContext:
                    summary: Rephrase text using DeepL API
