resources:
    RZ\Roadiz\CoreBundle\Api\Model\WebResponse:
        shortName: WebResponse
        types:
            - WebResponse
        filters:
            - app.property_filter
        operations:
            article_get_by_path:
                method: GET
                class: ApiPlatform\Metadata\Get
                uriTemplate: /web_response_by_path
                read: false
                controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
                normalizationContext:
                    pagination_enabled: false
                    enable_max_depth: true
                    groups:
                        - article_get_by_path
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - web_response
                        - walker
                        - walker_metadata
                        - children
                openapi:
                    tags:
                        - WebResponse
                    summary: 'Get a Article by its path wrapped in a WebResponse object'
                    description: 'Get a Article by its path wrapped in a WebResponse'
                    parameters:
                        - { type: string, name: path, in: query, required: true, description: 'Resource path, or `/` for home page', schema: { type: string } }
            articlecontainer_get_by_path:
                method: GET
                class: ApiPlatform\Metadata\Get
                uriTemplate: /web_response_by_path
                read: false
                controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
                normalizationContext:
                    pagination_enabled: false
                    enable_max_depth: true
                    groups:
                        - articlecontainer_get_by_path
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - web_response
                        - walker
                        - walker_metadata
                        - children
                openapi:
                    tags:
                        - WebResponse
                    summary: 'Get a ArticleContainer by its path wrapped in a WebResponse object'
                    description: 'Get a ArticleContainer by its path wrapped in a WebResponse'
                    parameters:
                        - { type: string, name: path, in: query, required: true, description: 'Resource path, or `/` for home page', schema: { type: string } }
            offer_get_by_path:
                method: GET
                class: ApiPlatform\Metadata\Get
                uriTemplate: /web_response_by_path
                read: false
                controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
                normalizationContext:
                    pagination_enabled: false
                    enable_max_depth: true
                    groups:
                        - offer_get_by_path
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - web_response
                        - walker
                        - walker_metadata
                        - children
                openapi:
                    tags:
                        - WebResponse
                    summary: 'Get a Offer by its path wrapped in a WebResponse object'
                    description: 'Get a Offer by its path wrapped in a WebResponse'
                    parameters:
                        - { type: string, name: path, in: query, required: true, description: 'Resource path, or `/` for home page', schema: { type: string } }
            page_get_by_path:
                method: GET
                class: ApiPlatform\Metadata\Get
                uriTemplate: /web_response_by_path
                read: false
                controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
                normalizationContext:
                    pagination_enabled: false
                    enable_max_depth: true
                    groups:
                        - page_get_by_path
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - nodes_sources_images
                        - nodes_sources_boolean
                        - nodes_sources_geo
                        - web_response
                        - walker
                        - walker_metadata
                        - children
                openapi:
                    tags:
                        - WebResponse
                    summary: 'Get a Page by its path wrapped in a WebResponse object'
                    description: 'Get a Page by its path wrapped in a WebResponse'
                    parameters:
                        - { type: string, name: path, in: query, required: true, description: 'Resource path, or `/` for home page', schema: { type: string } }
