controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

roadiz_core:
    resource: "@RoadizCoreBundle/config/routing.yaml"

roadiz_rozier:
    resource: "@RoadizRozierBundle/config/routing.yaml"

roadiz_font:
    resource: "@RoadizFontBundle/config/routing.yaml"

roadiz_two_factor:
    resource: "@RoadizTwoFactorBundle/config/routing.yaml"

rz_intervention_request:
    resource: "@RZInterventionRequestBundle/Resources/config/routing.yml"
    prefix:   /


api_contact_form_definition:
    methods: [GET]
    stateless: true
    path: /api/contact_form/definition
    defaults:
        _controller: App\Controller\ContactFormController::definitionAction
        _locale: fr
        _format: json

api_contact_form_post:
    methods: [POST]
    stateless: true
    path: /api/contact_form/post
    defaults:
        _controller: App\Controller\ContactFormController::formAction
        _locale: fr
        _format: json

public_login_link_check:
    path: /api/users/login_link_check
    methods: [POST]
