# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\ContactFormController:
        tags: [ 'controller.service_arguments' ]

    App\Serializer\Normalizer\MenuLinkPathNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
    # Need a different name to avoid duplicate YAML key
    app.serializer.normalizer.menu_link_path.json:
        class: 'App\Serializer\Normalizer\MenuLinkPathNormalizer'
        decorates: 'api_platform.serializer.normalizer.item'

    app.property_filter:
        parent: 'api_platform.serializer.property_filter'
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    App\Serializer\Normalizer\AliasBlockWalkerNormalizer:
        decorates: 'api_platform.jsonld.normalizer.object'
        arguments:
            $decorated: '@App\Serializer\Normalizer\AliasBlockWalkerNormalizer.inner'
            $itemNormalizer: '@api_platform.serializer.normalizer.item'

    RZ\Roadiz\RozierBundle\Translator\DeeplTranslatorController:
        arguments:
            $apiKey: '%env(string:DEEPL_API_KEY)%'
