/**
 * File auto-generated by Iconify plugin
 */
export default [
    'apple-podcasts',
    'dailymotion',
    'deezer',
    'excel',
    'facebook',
    'linkedin',
    'mixcloud',
    'soundcloud',
    'spotify',
    'ted',
    'vimeo',
    'youtube-line',
    'youtube',
]