/**
 * File auto-generated by Iconify plugin
 */
export default [
    'logo-rz',
    'status-archived-fill',
    'status-archived-line',
    'status-container-line',
    'status-deleted-fill',
    'status-deleted-line',
    'status-draft-fill',
    'status-draft-line',
    'status-lock-line',
    'status-no-index-line',
    'status-pending-line',
    'status-published-fill',
    'status-published-line',
    'status-shadow-container-line',
]
