/**
 * File auto-generated by Iconify plugin
 */
export default [
    'status-container',
    'status-draft-colored',
    'status-draft-outlined',
    'status-draft',
    'status-lock',
    'status-no-index',
    'status-published-colored',
    'status-published-outlined',
    'status-published',
    'status-shadow-container',
]