<?php

declare(strict_types=1);

namespace RZ\Roadiz\RozierBundle\Controller\User;

use Doctrine\Persistence\ManagerRegistry;
use RZ\Roadiz\Core\AbstractEntities\PersistableInterface;
use RZ\Roadiz\CoreBundle\Entity\User;
use RZ\Roadiz\CoreBundle\ListManager\EntityListManagerFactoryInterface;
use RZ\Roadiz\CoreBundle\Security\Authorization\Voter\UserVoter;
use RZ\Roadiz\CoreBundle\Security\LogTrail;
use RZ\Roadiz\RozierBundle\Controller\AbstractAdminWithBulkController;
use RZ\Roadiz\RozierBundle\Form\UserDetailsType;
use RZ\Roadiz\RozierBundle\Form\UserType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class UserController extends AbstractAdminWithBulkController
{
    public function __construct(
        FormFactoryInterface $formFactory,
        UrlGeneratorInterface $urlGenerator,
        EntityListManagerFactoryInterface $entityListManagerFactory,
        ManagerRegistry $managerRegistry,
        TranslatorInterface $translator,
        LogTrail $logTrail,
        EventDispatcherInterface $eventDispatcher,
        private readonly bool $useGravatar,
    ) {
        parent::__construct($formFactory, $urlGenerator, $entityListManagerFactory, $managerRegistry, $translator, $logTrail, $eventDispatcher);
    }

    #[\Override]
    protected function supports(PersistableInterface $item): bool
    {
        return $item instanceof User;
    }

    #[\Override]
    protected function getNamespace(): string
    {
        return 'user';
    }

    #[\Override]
    protected function createEmptyItem(Request $request): User
    {
        $user = new User();
        $user->sendCreationConfirmationEmail(true);

        return $user;
    }

    #[\Override]
    protected function getTemplateFolder(): string
    {
        return '@RoadizRozier/users';
    }

    #[\Override]
    protected function getRequiredRole(): string
    {
        return 'ROLE_ACCESS_USERS';
    }

    #[\Override]
    protected function getRequiredEditionRole(): string
    {
        // Allow any backoffice user to access user edition before
        // checking if current editing item is the same as current user.
        return 'ROLE_BACKEND_USER';
    }

    #[\Override]
    protected function getRequiredDeletionRole(): string
    {
        return 'ROLE_ACCESS_USERS_DELETE';
    }

    #[\Override]
    protected function getEntityClass(): string
    {
        return User::class;
    }

    #[\Override]
    protected function getFormType(): string
    {
        return UserType::class;
    }

    #[\Override]
    protected function getDefaultRouteName(): string
    {
        return 'usersHomePage';
    }

    #[\Override]
    protected function getEditRouteName(): string
    {
        return 'usersEditPage';
    }

    #[\Override]
    protected function getBulkDeleteRouteName(): ?string
    {
        return 'usersBulkDeletePage';
    }

    #[\Override]
    protected function denyAccessUnlessItemGranted(PersistableInterface $item): void
    {
        parent::denyAccessUnlessItemGranted($item);

        $this->denyAccessUnlessGranted(UserVoter::EDIT, $item);
    }

    #[\Override]
    protected function getEntityName(PersistableInterface $item): string
    {
        if (!$item instanceof User) {
            throw new \RuntimeException('Invalid item type.');
        }

        return $item->getUsername();
    }

    #[\Override]
    protected function getDefaultOrder(Request $request): array
    {
        return ['username' => 'ASC'];
    }

    #[\Override]
    protected function createUpdateEvent(PersistableInterface $item)
    {
        if (!$item instanceof User) {
            throw new \RuntimeException('Invalid item type.');
        }
        /*
         * If pictureUrl is empty, use default Gravatar image.
         */
        if ('' == $item->getPictureUrl() && $this->useGravatar) {
            $item->setPictureUrl($item->getGravatarUrl());
        }

        return parent::createUpdateEvent($item); // TODO: Change the autogenerated stub
    }

    public function editDetailsAction(Request $request, int $id): Response
    {
        $this->additionalAssignation($request);

        /** @var mixed|object|null $item */
        $item = $this->em()->find($this->getEntityClass(), $id);
        if (!($item instanceof PersistableInterface)) {
            throw $this->createNotFoundException();
        }

        $this->prepareWorkingItem($item);
        $this->denyAccessUnlessGranted(UserVoter::EDIT_DETAIL, $item);

        $form = $this->createForm(UserDetailsType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /*
             * Events are dispatched before entity manager is flushed
             * to be able to throw exceptions before it is persisted.
             */
            $event = $this->createUpdateEvent($item);
            $this->dispatchSingleOrMultipleEvent($event);
            $this->em()->flush();

            /*
             * Event that requires that EM is flushed
             */
            $postEvent = $this->createPostUpdateEvent($item);
            $this->dispatchSingleOrMultipleEvent($postEvent);

            $msg = $this->translator->trans(
                '%namespace%.%item%.was_updated',
                [
                    '%item%' => $this->getEntityName($item),
                    '%namespace%' => $this->translator->trans($this->getNamespace()),
                ]
            );
            $this->logTrail->publishConfirmMessage($request, $msg, $item);

            /*
             * Force redirect to avoid resending form when refreshing page
             */
            return $this->redirectToRoute(
                'usersEditDetailsPage',
                ['id' => $item->getId()]
            );
        }

        $this->assignation['form'] = $form->createView();
        $this->assignation['item'] = $item;

        return $this->render(
            $this->getTemplateFolder().'/editDetails.html.twig',
            $this->assignation,
        );
    }

    #[\Override]
    protected function additionalAssignation(Request $request): void
    {
        parent::additionalAssignation($request);

        if (null !== $this->getBulkEnableRouteName()) {
            $bulkEnableForm = $this->createEnableBulkForm(true);
            $this->assignation['bulkEnableForm'] = $bulkEnableForm->createView();
            $this->assignation['hasBulkActions'] = true;
        }

        if (null !== $this->getBulkDisableRouteName()) {
            $bulkDisableForm = $this->createDisableBulkForm(true);
            $this->assignation['bulkDisableForm'] = $bulkDisableForm->createView();
            $this->assignation['hasBulkActions'] = true;
        }
    }

    /*
     * User specific bulk actions
     */

    protected function createEnableBulkForm(bool $get = false, ?array $data = null): FormInterface
    {
        return $this->createBulkForm(
            $this->getBulkEnableRouteName(),
            'bulk-enable',
            $get,
            $data
        );
    }

    protected function createDisableBulkForm(bool $get = false, ?array $data = null): FormInterface
    {
        return $this->createBulkForm(
            $this->getBulkDisableRouteName(),
            'bulk-disable',
            $get,
            $data
        );
    }

    private function getBulkEnableRouteName(): string
    {
        return 'usersBulkEnablePage';
    }

    private function getBulkDisableRouteName(): string
    {
        return 'usersBulkDisablePage';
    }

    public function bulkEnableAction(Request $request): Response
    {
        return $this->bulkAction(
            $request,
            $this->getRequiredRole(),
            $this->createEnableBulkForm(true),
            $this->createEnableBulkForm(),
            fn (string $ids) => $this->createEnableBulkForm(false, [
                'id' => $ids,
            ]),
            $this->getTemplateFolder().'/bulk_enable.html.twig',
            '%namespace%.%item%.was_enabled',
            function (PersistableInterface $item) {
                if (!$item instanceof User) {
                    throw new \RuntimeException('Invalid item type.');
                }
                $item->setEnabled(true);
            },
            'bulkEnableForm'
        );
    }

    public function bulkDisableAction(Request $request): Response
    {
        return $this->bulkAction(
            $request,
            $this->getRequiredRole(),
            $this->createDisableBulkForm(true),
            $this->createDisableBulkForm(),
            fn (string $ids) => $this->createDisableBulkForm(false, [
                'id' => $ids,
            ]),
            $this->getTemplateFolder().'/bulk_disable.html.twig',
            '%namespace%.%item%.was_disabled',
            function (PersistableInterface $item) {
                if (!$item instanceof User) {
                    throw new \RuntimeException('Invalid item type.');
                }
                $item->setEnabled(false);
            },
            'bulkDisableForm'
        );
    }
}
