name: Unit tests, static analysis and code style

on:
    push:
        branches:
            - develop
            - 'release/**'
            - 'hotfix/**'
        tags: ['**']
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.1', '8.2', '8.3']
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - uses: actions/checkout@v3
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-${{ matrix.php-version }}-
            - name: Install Dependencies
              run: composer install --no-scripts --no-ansi --no-interaction --no-progress
            - name: Validate monorepo
              run: |
                  vendor/bin/monorepo-builder validate
            - name: Run unit tests
              run: |
                  vendor/bin/atoum -d ./lib/Documents/tests
                  vendor/bin/atoum -f ./lib/EntityGenerator/tests/units/*
                  vendor/bin/phpunit -v  lib/Models/tests
            - name: Run PHP Code Sniffer
              run: |
                  php -d "memory_limit=-1" vendor/bin/phpcs --report=full -p
            - name: Run PHP Stan
              run: |
                  php -d "memory_limit=-1" vendor/bin/phpstan analyse -c phpstan.neon
            - name: Run Twig lint
              run: |
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/Rozier/src/Resources/views
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/Documents/src/Resources/views
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/RoadizUserBundle/templates
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/RoadizRozierBundle/templates
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/RoadizFontBundle/templates
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/RoadizCoreBundle/templates
                  php -d "memory_limit=-1" bin/console lint:twig ./lib/RoadizTwoFactorBundle/templates
